# Generated by Django 6.0.1 on 2026-01-31 14:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Prompt categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WritingGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('time', 'Minutes per session'), ('words', 'Words per session'), ('sessions', 'Number of sessions')], default='time', max_length=10)),
                ('target_value', models.PositiveIntegerField(help_text='Target value (minutes, words, or sessions)', validators=[django.core.validators.MinValueValidator(1)])),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for ongoing goals', null=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Why did you set this goal? What are you working towards?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WritingPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy (5-10 minutes)'), ('medium', 'Medium (15-20 minutes)'), ('deep', 'Deep (30+ minutes)')], default='medium', max_length=15)),
                ('prompt_type', models.CharField(choices=[('journal', 'Journal Entry'), ('memoir', 'Memoir/Memory'), ('both', 'Both')], default='both', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='prompt.promptcategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='prompts', to='prompt.tag')),
            ],
        ),
        migrations.CreateModel(
            name='WritingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('minutes_spent', models.PositiveIntegerField(help_text='How many minutes did you spend writing?', validators=[django.core.validators.MinValueValidator(1)])),
                ('word_count', models.PositiveIntegerField(default=0, help_text='Approximately how many words did you write? (Optional)')),
                ('prompt_used', models.TextField(blank=True, null=True)),
                ('mood', models.CharField(choices=[('very_negative', 'Very Difficult'), ('negative', 'Difficult'), ('neutral', 'Neutral'), ('positive', 'Enjoyable'), ('very_positive', 'Very Enjoyable')], default='neutral', help_text='How was your writing session?', max_length=15)),
                ('notes', models.TextField(blank=True, help_text='What did you write about? How did it go?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
