# Generated by Django 5.1.6 on 2025-03-31 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0002_writinggoal_writingsession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promptcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Prompt categories'},
        ),
    ]
