# Generated by Django 5.2.1 on 2025-07-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0003_alter_promptcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingsession',
            name='prompt_used',
            field=models.TextField(blank=True, null=True),
        ),
    ]
