# Generated by Django 5.1 on 2025-03-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resource',
            field=models.FileField(blank=True, null=True, upload_to='blog/resources/'),
        ),
        migrations.AddField(
            model_name='post',
            name='resource_title',
            field=models.CharField(blank=True, help_text='Title for the downloadable resource', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='resource_type',
            field=models.CharField(choices=[('none', 'No Resource'), ('pdf', 'PDF Document')], default='none', max_length=20),
        ),
    ]
