# Generated by Django 5.1 on 2025-03-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_resource_post_resource_title_post_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ad_image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/'),
        ),
    ]
